---
title: "fiddler_crab"
author: "Julia Parish"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(kableExtra)

```

```{r}
crab_size <- read_csv(here("data", "FiddlerCrabBodySize.csv")) %>%
  clean_names()
```

```{r, echo=FALSE, fig.alt="A scatter plot showing the mean carapice width measured daily growing as the mean annual water temperature drops."}

daily_summary <- crab_size %>% 
  group_by(date) %>% 
  summarize(daily_carapice_width = mean(carapace_width), daily_matw = mean(matw))


ggplot(data = daily_summary, aes(x = daily_carapice_width, y = daily_matw)) +
  geom_point(aes(color = daily_carapice_width), show.legend = FALSE) +
  labs(x = "Mean Carapice Width",
       y = "Mean Annual Water Temp", 
       title = "Fiddler Crab Carapice Width Influenced By Mean Annual Water Temperature", 
       caption = "Data sourced from: https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-pie.540.1")
```

```{r, echo=FALSE}
crab_summary <- crab_size %>% 
  group_by(site) %>% 
  summarize(mean = round(mean(carapace_width), 2),
            sd = round(sd(carapace_width),2),
            sample_size = n())
```

```{r, echo=FALSE}
crab_table <- crab_summary %>% 
  kable(col.names = c("Site Location", "Mean Carapace Width (mm)", "Carapace Width Std Dev (mm)", "Sample Size")) %>% 
  kable_minimal(full_width = FALSE)

crab_table


```


